  spring:
    h2.console:
      enabled: true
      path: '/console'
    datasource:
      url: 'jdbc:h2:file:C:/Users/DESTIN/Desktop/SimpleToDoWebApp/SimpleToDoWebApp/todo-db'
    jpa:
      hibernate:
        ddl-auto: validate
